# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# Workflow for training models when new data is added or preprocessing or training classes are modified

name: Train Models

on:
  push:
    branches: [ "main" ]
    paths:
      - 'data/**'
      - 'ai-utils/src/main/java/**'
    # - '.github/workflows/train-models.yml'

jobs:
  data-preprocess:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
      - name: Maven Build Model Module
        run: mvn clean install -pl model -am

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # or any supported version

      - name: Install DVC
        run: pip install dvc

      - name: DVC Extras
        run: pip install 'dvc[gdrive]'

      - name: Create Key
        run: echo '${{ secrets.GDRIVE_KEY }}' > gdrive_key.json

      - name: DVC Pull
        run: dvc pull

      - name: Process Data
        run: mvn exec:java -pl ai-utils -Dexec.mainClass="data.DataPreprocessor" -Dexec.args="data/raw_klines.csv data/processed_dataset.csv"

      - uses: actions/upload-artifact@v4
        with:
          name: processed-dataset-artifact
          path: data/processed_dataset.csv


  train-models:
    runs-on: ubuntu-latest
    needs: data-preprocess
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
      - name: Maven Build Model Module
        run: mvn clean install -pl model -am

      - uses: actions/download-artifact@v4
        with:
          name: processed-dataset-artifact
          path: data/

      - name: Train Linear Regression Model
        run: mvn exec:java -pl ai-utils -Dexec.mainClass="trainer.LinearRegressionTrainer" -Dexec.args="data/processed_dataset.csv"

      - name: Train Random Forest Regressor Model
        run: mvn exec:java -pl ai-utils -Dexec.mainClass="trainer.RandomForestRegressorTrainer" -Dexec.args="data/processed_dataset.csv"